[program:jsd-messenger]
command=/usr/bin/php8.4 /home/jsd-deploy/html/current/bin/console messenger:consume async --time-limit=3600 --memory-limit=128M
user=jsd-deploy
numprocs=1
autostart=true
autorestart=true
startsecs=0
startretries=10
stopsignal=TERM
process_name=%(program_name)s_%(process_num)02d
stderr_logfile=/home/jsd-deploy/log/messenger-error.log
stdout_logfile=/home/jsd-deploy/log/messenger.log
