hosts:
  'staging':
    stage: staging
    roles: 'app db web'
    deploy_path: ~/html
    remote_user: support2025
    hostname: support2025.sf.preprod.spiriit.tech
    branch: develop
    symfony_env: staging
  'prod':
    stage: prod
    roles: 'app db web'
    deploy_path: ~/html
    remote_user: support2025
    hostname: prod01.infra.spiriit.net
    branch: main
    symfony_env: prod
