.staging: &staging
  stage: staging
  symfony_env: staging
  branch: develop
  deploy_path: ~/html
  remote_user: jsd-deploy

.prod: &prod
  stage: prod
  symfony_env: prod
  branch: main
  deploy_path: ~/html
  remote_user: jsd-deploy

hosts:
  'staging':
    <<: *staging
    hostname: jsd.preprod.spiriit.tech
    database_migration: true
    messenger_rerun: true
    labels:
      env: staging
  'prod':
    <<: *prod
    hostname: jsd.prod.spiriit.tech
    database_migration: true
    messenger_rerun: true
    labels:
      env: prod
